spring:
  profiles:
    active: db
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  config: classpath:config/log4j2.xml

mybatis:
  mapper-locations: classpath*:/sqlmappers/*.xml
  executor-type: SIMPLE
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 120
server:
  port: 9000
